version: '2'

services:
  web:
    build:
        context: .
        restart: always
        dockerfile: Dockerfile
        args:
            GITHASH: 1e28976bd152e659d4eebfa763259abad82ef8ff
    environment:
        - serviceRootUrl=http://smartaqnet.teco.edu:8080/FROST-Server
        - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
        - persistence_idGenerationMode=ServerAndClientGenerated
        - persistence_db_jndi_datasource=
        - persistence_db_driver=org.postgresql.Driver
        - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
        - persistence_db_username=sensorthings
        - persistence_db_password=ChangeMe
    ports:
      - "8080:8080"
      - "1883:1883"
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    ports:
        - "5432:5432"
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
